### PR TITLE
Merging `$data` with `$fields` to support FCM properly

### PR DESCRIPTION
**Pull request by nostop8**
Allowing to provide proper structure to FCM service. Before all the payload was wrapped with `data` property, which makes impossible to send proper payload structure, where `notification` property should be in the root of payload.
The payload for android should look like this: 
```
{  
   "registration_ids":[  
      "fzdtQx55LPU:APA91bFrwA7NgsKlgTkpYD_uVVPe5hTO8OLISpNvAU5Q_u4bdUU3q0jo8Cf-2-JNOvq-xhK9TawLM7nZ5KOH3hOQUjYLy9sO4vHNbcpU0Yex3EgS5W2YXws8olK-3NWlKmLAtPSu2thM"
   ],
   "notification":{  
      "body":"Body for app in background",
      "title":"Title for app in background",
      "icon":"1",
      "sound":1,
      "priority":"high"
   },
   "data":{  
      "body":"Body for app in foreground",
      "title":"Title for app in foreground",
   }
}
```

### CODE REVIEW

**Comment by bit-crafter** [comment]
The change you want to be made  will affect on other version. We suggest another solution which is.

carbon 2

**Comment by nostop8** [comment]
I do not mind and I agree with that. I was also thinking about this solution. Still, you need to consider that except of `data` and `notification` properties, there might be other. In this case you will need to add even more parameters into sendGcm method in future. So, on one hand you have possibility to provide backwards compatibility and maintain possible to issues related to payload or else you may drop backwards compatibility but forgot about issues related to Firebase Cloud Messaging payload, but probably you will get issues from guys who use FCM and updated the module. BTW, you need to update GCM prefixes to FCM, because it is rather confusing.

**Comment by bit-crafter** [comment]
@nostop8  
We can add send FCM function with support of new changes and mark sendGCM as an deprecated and remove it in future releases. 
What do you think about that ?

**Comment by nostop8** [comment]
@tumdav I think its great idea!

**Comment by nostop8** [comment]
@tumdav when do you plan to update this or do you want me to apply this changes?

**Comment by bit-crafter** [comment]
@nostop8 please change PR if it's not hard for you. :)

**Comment by nostop8** [comment]
@tumdav I've added new method for sending messages using firebase properly, also added corresponding constants and variables using template from previous message providers. Except of this added example to the readme file. Tested this with android, one and multiple tokens - works well. Firebase also supports ios as you may know and from documentation seems that same payload structure is required. I've mentioned this inside new example.

**Pull request merged**
